#TODO check if war is allredy present - If so fail and prompt user to use the uprade instead 

- name: Download Artemis.war to {{ artemis_working_directory }}
  become: true
  get_url:
    url: "{{ artemis_war_url }}"
    dest: "{{ artemis_working_directory }}/artemis.war"
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
    mode: '0644'
  notify: restart artemis

