- name: Check if broker is installed
  stat:
    path: "{{ activemq_working_directory }}"
  register: broker_install_result

- name: Create broker in {{ activemq_working_directory }} (NOT IDEMPOTENT)
  command: ./artemis create --user {{ activemq_username }} --password {{ activemq_password }} --require-login --force {{ activemq_working_directory }}
  args:
    chdir: "{{ activemq_install_directory }}/apache-artemis-{{ activemq_version }}/bin"
  notify: restart broker
  when: not broker_install_result.stat.exists

- name: Copy primary broker.xml file
  template:
    src: activemq_primary_broker.xml.j2
    dest: "{{ activemq_working_directory }}/etc/broker.xml"
    mode: 0644

- name: Set permissions for broker working directory
  file:
    path: "{{ activemq_working_directory }}"
    state: directory
    recurse: yes
    owner: "{{ artemis_user_name }}"
    group: "{{ artemis_user_group }}"
  notify: restart broker

- name: Copy broker1.service systemd configuration
  template:
    src: activemq_broker1.service.j2
    dest: "/etc/systemd/system/broker1.service"
    mode: 0644
  notify: restart broker

- name: Ensure correct broker version is installed
  lineinfile:
    path: "{{ activemq_working_directory }}/etc/artemis.profile"
    regexp: '^ARTEMIS_HOME='
    line: "ARTEMIS_HOME='/opt/activemq-distribution/apache-artemis-{{ activemq_version }}'"
  notify: restart broker

- name: Enable broker1 service
  systemd:
    daemon_reload: yes
    name: broker1
    enabled: yes
    masked: no
  notify: restart broker
