- name: Ensure group {{ artemis_user_group }} exists
  group:
    name: "{{ artemis_user_group }}"
    gid: "{{ artemis_user_gid }}"
    state: present

- name: Ensure user {{ artemis_user_name }} exists
  become: yes
  user:
    name: "{{ artemis_user_name }}"
    comment: "{{ artemis_user_comment }}"
    state: present
    uid: "{{ artemis_user_uid }}"
    group: "{{ artemis_user_group }}"
