---

- name: Create database user with password and PROCESS, REPLICATION CLIENT privileges
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT'
    state: present

- name: Install mysqld_exporter
  include_role:
    name: cloudalchemy.mysqld_exporter
  vars:
    mysqld_exporter_version: "{{ mysql_exporter_version }}"
    mysqld_exporter_dsn: "{{ mysql_exporter_dsn }}"

