- name: reload nginx
  become: true
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: apply sysctl
  become: true
  command: sysctl -p

- name: reboot system
  become: true
  reboot:
